core/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [url(r'', include('dashboard.urls')), url(r'^admin/', admin.site.urls), ]

dashboard/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
]

project/models/chance.py
from django.db import models


class Chance(models.Model):
    COST_CHOICES = ((1, 'Low'), (2, 'High'), (3, 'Very High'),)
    IMPACT_CHOICES = ((1, 'Small'), (2, 'Big'), (3, 'Very Big'),)

    project = models.ForeignKey(to='project.Project', related_name='chances', related_query_name='chance', )
    name = models.CharField(verbose_name='Name', max_length=50, )
    date = models.DateField(verbose_name='Discovery Date', )
    cost = models.PositiveIntegerField(verbose_name='Cost of the Chance', choices=COST_CHOICES)
    impact = models.PositiveIntegerField(verbose_name='Impact of the Chance', choices=IMPACT_CHOICES)
    used = models.BooleanField(verbose_name='Chance used', default=False)

    def __str__(self):
        return self.name

project/models/risk.py
from django.db import models


class Risk(models.Model):
    PROBABILITY_CHOICES = ((1, 'Low'), (2, 'High'), (3, 'Very High'),)
    SEVERITY_CHOICES = ((1, 'Low'), (2, 'High'), (3, 'Very High'),)
    RISK_MAP = {
        1: 'Very Low',
        2: 'Low',
        3: 'Medium',
        4: 'High',
        6: 'Very High',
        9: 'Extremely High',
    }

    project = models.ForeignKey(to='project.Project', related_name='risks', related_query_name='risk', )
    name = models.CharField(verbose_name='Name', max_length=50, )
    date = models.DateField(verbose_name='Discovery Date', )
    probability = models.PositiveIntegerField(verbose_name='Probability of the Risk', choices=PROBABILITY_CHOICES)
    severity = models.PositiveIntegerField(verbose_name='Severity of the Risk', choices=SEVERITY_CHOICES)
    counter_measurement = models.TextField(verbose_name='Counter Measurement', )
    resolved = models.BooleanField(verbose_name='Risk resolved', default=False)

    def get_risk(self):
        return self.severity * self.probability

    def display_risk(self):
        return self.RISK_MAP.get(self.get_risk())

    def __str__(self):
        return self.name

dashboard/views.py
from django.shortcuts import render
from project.models import Project
from datetime import date


def calculate_time_status(project):
    planned_duration = project.get_planned_duration()
    duration = project.get_duration()
    delta = planned_duration - duration
    if delta >= 0:
        return 1
    missmatch = abs((planned_duration / duration) - 1)
    if missmatch <= 0.05:
        return 2
    return 3


def calculate_budget_status(project, date):
    planned_cost = project.get_planned_cost(date)
    actual_cost = project.get_cost(date)
    delta = planned_cost - actual_cost
    if delta >= 0:
        return 1
    missmatch = abs((planned_cost / actual_cost) - 1)
    if missmatch <= 0.05:
        return 2
    return 3


def calculate_scope_status(project, date):
    risk = project.get_unresolved_risk(on_date=date)
    if risk < 3:
        return 1
    if risk == 3:
        return 2
    return 3


def index(request):
    project = Project.objects.all().prefetch_related('phases__tasks__duration_predictions').prefetch_related(
        'phases__tasks__resources').last()
    today = project.today()
    planned_cost = project.get_planned_cost(today)
    actual_cost = project.get_cost(today)
    earned_value = project.get_earnings(today)
    context = {
        'project': project,
        'cost': {
            'planned': planned_cost,
            'actual': actual_cost,
            'earning': earned_value,
            'variance': earned_value - actual_cost,
            'cpi': earned_value / actual_cost,
        },
        'status': {
            'time': calculate_time_status(project),
            'budget': calculate_budget_status(project, today),
            'scope': calculate_scope_status(project, today),
        }
    }

    return render(request=request, template_name='dashboard/dashboard.html', context=context)

dashboard/templates/dashboard/sections/tabs/budget-earned-value-analyis-graph.html
{% load budget_earned_value_analysis %}

<div id="eva_div" class="uk-width-1-1"></div>

<script type="text/javascript">
    google.charts.setOnLoadCallback(drawEarnedValueAnalysisChart);

    function drawEarnedValueAnalysisChart() {
        var data = new google.visualization.DataTable();
        data.addColumn('date', 'Date of Prediction');
        data.addColumn('number', 'Planned Cost');
        data.addColumn('number', 'Actual Cost');
        data.addColumn('number', 'Predicted Cost');
        data.addColumn('number', 'Earned Value');


        var rows = {% autoescape off %}{% get_table project %}{% endautoescape %};
        data.addRows(rows);

        var options = {
            height: 500,
            explorer: {
                actions: ['dragToPan', 'dragToPan', 'rightClickToReset']
            },
            vAxis: {
                title:'Cost in CHF'
            },
            hAxis: {
                format: 'dd.MM.yyyy'
            },
        };

        var chart = new google.charts.Line(document.getElementById('eva_div'));

        chart.draw(data, google.charts.Line.convertOptions(options));

    }
</script>

dashboard/templates/dashboard/sections/tabs/budget-earnings.html
{% load budget %}

<table class="uk-table uk-table-striped uk-table-hover uk-table-small">
    <thead>
    <tr>
        <th>ID</th>
        <th>Date</th>
        <th>Contract Milestone</th>
        <th>Spent</th>
        <th>Earned</th>
        <th>Earned / Spent Ratio</th>
    </tr>
    </thead>
    <tbody>
    {% for earning in project.earnings.all %}
        {% if earning.date <= project.today %}
            <tr>
                <td>E{{ earning.id }}</td>
                <td>{{ earning.date }}</td>
                <td>{{ earning.name }}</td>
                <td>{{ earning|cost:project|floatformat:2 }} CHF</td>
                <td>{{ earning.value|floatformat:2 }} CHF</td>
                <td>{{ earning|contract_delta:project|floatformat:2 }}</td>
                <td></td>
            </tr>
        {% endif %}
    {% endfor %}
    </tbody>
</table>

dashboard/templates/dashboard/sections/tabs/budget-phases.html
{% load budget %}

<table class="uk-table uk-table-striped uk-table-hover uk-table-small">
    <thead>
    <tr>
        <th>ID</th>
        <th>Phase</th>
        <th>Planned Duration</th>
        <th>Actual Duration</th>
        <th>Planned Cost</th>
        <th>Actual Cost</th>
        <th>Actual / Planned Ratio</th>
    </tr>
    </thead>
    <tbody>
    {% for phase in project.phases.all %}
        {% if phase.get_end_date <= project.today %}
            <tr>
                <td>P{{ phase.id }}</td>
                <td>{{ phase.name }}</td>
                <td>{{ phase.get_planned_duration }} days</td>
                <td>{{ phase.get_duration }} days</td>
                <td>{{ phase.get_planned_cost|floatformat:2 }} CHF</td>
                <td>{{ phase.get_cost|floatformat:2 }} CHF</td>
                <td>{{ phase|phase_cost_delta|floatformat:2 }}</td>
            </tr>
        {% endif %}
    {% endfor %}
    </tbody>
</table>

dashboard/templates/dashboard/sections/tabs/budget-resources.html
{% load budget %}

<table class="uk-table uk-table-striped uk-table-hover uk-table-small">
    <thead>
    <tr>
        <th>ID</th>
        <th>Resource</th>
        <th>Daily Cost</th>
        <th>Planned Usage</th>
        <th>Actual Usage</th>
        <th>Planned Cost</th>
        <th>Actual Cost</th>
        <th>Actual / Planned Ratio</th>
    </tr>
    </thead>
    <tbody>
    {% for resource in project.resources %}
        <tr>
            <td>R{{ resource.id }}</td>
            <td>{{ resource.name }}</td>
            <td>{{ resource.cost|floatformat:2  }} CHF</td>
            <td>{{ resource|planned_resource_duration:project }} days</td>
            <td>{{ resource|resource_duration:project }} days</td>
            <td>{{ resource|planned_resource_cost:project|floatformat:2 }} CHF</td>
            <td>{{ resource|resource_cost:project|floatformat:2 }} CHF</td>
            <td>{{ resource|resource_cost_delta:project|floatformat:2 }}</td>
        </tr>
    {% endfor %}
    </tbody>
</table>

dashboard/templates/dashboard/sections/tabs/scope-chances.html
<table class="uk-table uk-table-striped uk-table-hover uk-table-small">
    <thead>
    <tr>
        <th>ID</th>
        <th>Chance</th>
        <th>Discovered</th>
        <th>Cost</th>
        <th>Impact</th>
        <th>Used</th>
    </tr>
    </thead>
    <tbody>
    {% for chance in project.chances.all %}
        {% if chance.date <= project.today %}
            <tr>
                <td>C{{ chance.id }}</td>
                <td>{{ chance.name }}</td>
                <td>{{ chance.date }}</td>
                <td>{{ chance.get_cost_display }}</td>
                <td>{{ chance.get_impact_display }}</td>
                <td>{% include 'dashboard/partials/boolean.html' with value=chance.used %}</td>
            </tr>
        {% endif %}
    {% endfor %}
    </tbody>
</table>

dashboard/templates/dashboard/sections/tabs/scope-issues.html
<table class="uk-table uk-table-striped uk-table-hover uk-table-small">
    <thead>
    <tr>
        <th>ID</th>
        <th>Issue</th>
        <th>Encountered</th>
        <th>Severity</th>
        <th>Counter Measurement</th>
    </tr>
    </thead>
    <tbody>
    {% for issue in project.issues.all %}
        {% if issue.date <= project.today %}
            <tr>
                <td>I{{ issue.id }}</td>
                <td>{{ issue.name }}</td>
                <td>{{ issue.date }}</td>
                <td>{{ issue.get_severity_display }}</td>
                <td>{{ issue.counter_measurement }}</td>
            </tr>
        {% endif %}
    {% endfor %}
    </tbody>
</table>

dashboard/templates/dashboard/sections/tabs/scope-risks.html
<table class="uk-table uk-table-striped uk-table-hover uk-table-small">
    <thead>
    <tr>
        <th>ID</th>
        <th>Issue</th>
        <th>Discovered</th>
        <th>Probability</th>
        <th>Severity</th>
        <th>Risk</th>
        <th>Counter Measurement</th>
        <th>Resolved</th>
    </tr>
    </thead>
    <tbody>
    {% for risk in project.risks.all %}
        {% if risk.date <= project.today %}
            <tr>
                <td>RSK{{ risk.id }}</td>
                <td>{{ risk.name }}</td>
                <td>{{ risk.date }}</td>
                <td>{{ risk.get_probability_display }}</td>
                <td>{{ risk.get_severity_display }}</td>
                <td>{{ risk.display_risk }}</td>
                <td>{{ risk.counter_measurement }}</td>
                <td>{% include 'dashboard/partials/boolean.html' with value=risk.resolved %}</td>
            </tr>
        {% endif %}
    {% endfor %}
    </tbody>
</table>

dashboard/templates/dashboard/sections/tabs/time-details.html
<table class="uk-table uk-table-striped uk-table-hover uk-table-small">
    <thead>
    <tr>
        <th>Phase</th>
        <th>Planned End</th>
        <th>Predicted End</th>
    </tr>
    </thead>
    <tbody>
    {% for phase in project.phases.all %}
        <tr>
            <td>{{ phase.name }}</td>
            <td>{{ phase.get_planned_end_date }}</td>
            <td>{{ phase.get_end_date }}</td>
        </tr>
    {% endfor %}
    </tbody>
</table>

dashboard/templates/dashboard/sections/tabs/time-milestone-trend-analysis-graph.html
{% load time_milestone_trend_analysis %}

<div id="mta_div" class="uk-width-1-1"></div>

<script type="text/javascript">
    google.charts.setOnLoadCallback(drawMilestoneTrendAnalysisChart);

    function drawMilestoneTrendAnalysisChart() {
        var data = new google.visualization.DataTable();
        {% get_headers project as headers %}
        {% autoescape off %}
            {% for header in headers %}
                data.addColumn('date', "{{ header }}");
            {% endfor %}
        {% endautoescape %}


        var rows = {% autoescape off %}{% get_table project %}{% endautoescape %};
        data.addRows(rows);

        var options = {
            height: 500,
            explorer: {
                actions: ['dragToPan', 'dragToPan', 'rightClickToReset']
            },
            vAxis: {
                format: 'dd.MM.yyyy',
                title:'Milestone Date'
            },
            hAxis: {
                format: 'dd.MM.yyyy'
            },
        };

        var chart = new google.charts.Line(document.getElementById('mta_div'));

        chart.draw(data, google.charts.Line.convertOptions(options));

    }
</script>

dashboard/templates/dashboard/sections/tabs/time-phases.html
{% load time_phases %}

<table class="uk-table uk-table-striped uk-table-hover uk-table-small">
    <thead>
    <tr>
        <th>ID</th>
        <th>Phase</th>
        <th>Planned End</th>
        <th>Predicted End</th>
        <th>Delta</th>
    </tr>
    </thead>
    <tbody>
    {% for phase in project.phases.all %}
        <tr>
            <td>P{{ phase.id }}</td>
            <td>{{ phase.name }}</td>
            <td>{{ phase.get_planned_end_date }}</td>
            <td>{{ phase.get_end_date }}</td>
            <td>{% delta_in_days phase %}</td>
        </tr>
    {% endfor %}
    </tbody>
</table>

dashboard/templates/dashboard/sections/tabs/time-project-gantt.html
{% load time_gantt %}

<div id="gantt_div" class="uk-width-1-1"></div>

<script type="text/javascript">
    google.charts.setOnLoadCallback(drawProjectGanttChart);


    function drawProjectGanttChart() {
        function daysToMilliseconds(days) {
            return days * 24 * 60 * 60 * 1000;
        }

        var data = new google.visualization.DataTable();
        data.addColumn('string', 'Task ID');
        data.addColumn('string', 'Task Name');
        data.addColumn('string', 'Resource ID');
        data.addColumn('date', 'Start Date');
        data.addColumn('date', 'End Date');
        data.addColumn('number', 'Duration');
        data.addColumn('number', 'Percent Complete');
        data.addColumn('string', 'Dependencies');

        var rows = [
            {% autoescape off %}
                {% for phase in project.phases.all %}
                    {% print_phase_row phase %}
                    {% for task in phase.tasks.all %}
                        {% print_task_row task %}
                    {% endfor %}
                {% endfor %}
            {% endautoescape %}
        ];

        data.addRows(rows);

        var el = document.getElementById('gantt_div');
        var chart = new google.visualization.Gantt(el);
        var options = {
            width: document.getElementById('time-tabs').getBoundingClientRect().width,
            height: rows.length * 42,
            gantt: {
                barCornerRadius: 0,
                percentEnabled: false
            }
        };
        chart.draw(data, options);


    }
</script>